CREATE USER USER_ADMIN IDENTIFIED BY admin123;
GRANT CREATE SESSION TO USER_ADMIN;
GRANT ADMIN_AEROPORT TO USER_ADMIN;

CREATE USER USER_ENREG IDENTIFIED BY enreg123;
GRANT CREATE SESSION TO USER_ENREG;
GRANT AGENT_ENREGISTREMENT TO USER_ENREG;

CREATE USER USER_CONTROLE IDENTIFIED BY ctrl123;
GRANT CREATE SESSION TO USER_CONTROLE;
GRANT AGENT_CONTROLE TO USER_CONTROLE;

CREATE USER USER_VOL IDENTIFIED BY vol123;
GRANT CREATE SESSION TO USER_VOL;
GRANT RESPONSABLE_VOLS TO USER_VOL;

CREATE USER USER_MAINT IDENTIFIED BY maint123;
GRANT CREATE SESSION TO USER_MAINT;
GRANT RESPONSABLE_MAINTENANCE TO USER_MAINT;

CREATE USER USER_BILLET IDENTIFIED BY billet123;
GRANT CREATE SESSION TO USER_BILLET;
GRANT AGENT_BILLETERIE TO USER_BILLET;

CREATE USER USER_LOGER IDENTIFIED BY loger123;
GRANT CREATE SESSION TO USER_LOGER;
GRANT LOGER TO USER_LOGER;
