-- Roles
CREATE ROLE ADMIN_AEROPORT;
CREATE ROLE AGENT_ENREGISTREMENT;
CREATE ROLE AGENT_CONTROLE;
CREATE ROLE RESPONSABLE_VOLS;
CREATE ROLE RESPONSABLE_MAINTENANCE;
CREATE ROLE AGENT_BILLETERIE;
CREATE ROLE LOGER;

-- LOGER can log in
GRANT CREATE SESSION TO LOGER;

-- ADMIN_AEROPORT: full access to AE tables
GRANT SELECT, INSERT, UPDATE, DELETE ON AE.PASSENGERS   TO ADMIN_AEROPORT;
GRANT SELECT, INSERT, UPDATE, DELETE ON AE.FLIGHTS      TO ADMIN_AEROPORT;
GRANT SELECT, INSERT, UPDATE, DELETE ON AE.AIRCRAFTS    TO ADMIN_AEROPORT;
GRANT SELECT, INSERT, UPDATE, DELETE ON AE.RESERVATIONS TO ADMIN_AEROPORT;
GRANT SELECT, INSERT, UPDATE, DELETE ON AE.MAINTENANCE  TO ADMIN_AEROPORT;

-- AGENT_ENREGISTREMENT
GRANT SELECT, INSERT, UPDATE ON AE.PASSENGERS   TO AGENT_ENREGISTREMENT;
GRANT SELECT, INSERT, UPDATE ON AE.RESERVATIONS TO AGENT_ENREGISTREMENT;
GRANT SELECT               ON AE.FLIGHTS       TO AGENT_ENREGISTREMENT;

-- AGENT_CONTROLE
GRANT SELECT ON AE.PASSENGERS TO AGENT_CONTROLE;
GRANT SELECT ON AE.FLIGHTS    TO AGENT_CONTROLE;

-- RESPONSABLE_VOLS
GRANT SELECT, INSERT, UPDATE, DELETE ON AE.FLIGHTS   TO RESPONSABLE_VOLS;
GRANT SELECT                         ON AE.AIRCRAFTS TO RESPONSABLE_VOLS;

-- RESPONSABLE_MAINTENANCE
GRANT SELECT, INSERT, UPDATE ON AE.MAINTENANCE TO RESPONSABLE_MAINTENANCE;
GRANT SELECT, UPDATE         ON AE.AIRCRAFTS   TO RESPONSABLE_MAINTENANCE;

-- AGENT_BILLETERIE
GRANT SELECT, UPDATE ON AE.RESERVATIONS TO AGENT_BILLETERIE;
GRANT SELECT         ON AE.FLIGHTS      TO AGENT_BILLETERIE;
GRANT SELECT         ON AE.PASSENGERS   TO AGENT_BILLETERIE;


CREATE USER USER_ADMIN  IDENTIFIED BY admin123;
GRANT CREATE SESSION TO USER_ADMIN;
GRANT ADMIN_AEROPORT TO USER_ADMIN;

CREATE USER USER_ENREG  IDENTIFIED BY enreg123;
GRANT CREATE SESSION TO USER_ENREG;
GRANT AGENT_ENREGISTREMENT TO USER_ENREG;

CREATE USER USER_CONTROLE IDENTIFIED BY ctrl123;
GRANT CREATE SESSION TO USER_CONTROLE;
GRANT AGENT_CONTROLE TO USER_CONTROLE;

CREATE USER USER_VOL IDENTIFIED BY vol123;
GRANT CREATE SESSION TO USER_VOL;
GRANT RESPONSABLE_VOLS TO USER_VOL;

CREATE USER USER_MAINT IDENTIFIED BY maint123;
GRANT CREATE SESSION TO USER_MAINT;
GRANT RESPONSABLE_MAINTENANCE TO USER_MAINT;

CREATE USER USER_BILLET IDENTIFIED BY billet123;
GRANT CREATE SESSION TO USER_BILLET;
GRANT AGENT_BILLETERIE TO USER_BILLET;

CREATE USER USER_LOGER IDENTIFIED BY loger123;
GRANT CREATE SESSION TO USER_LOGER;
GRANT LOGER TO USER_LOGER;

-- Quotas (optional)
ALTER USER USER_ADMIN  QUOTA UNLIMITED ON USERS;
ALTER USER USER_ENREG  QUOTA UNLIMITED ON USERS;
ALTER USER USER_CONTROLE QUOTA UNLIMITED ON USERS;
ALTER USER USER_VOL    QUOTA UNLIMITED ON USERS;
ALTER USER USER_MAINT  QUOTA UNLIMITED ON USERS;
ALTER USER USER_BILLET QUOTA UNLIMITED ON USERS;
ALTER USER USER_LOGER  QUOTA 0 ON USERS;


-- Public synonyms
CREATE PUBLIC SYNONYM PASSENGERS   FOR AE.PASSENGERS;
CREATE PUBLIC SYNONYM FLIGHTS      FOR AE.FLIGHTS;
CREATE PUBLIC SYNONYM AIRCRAFTS    FOR AE.AIRCRAFTS;
CREATE PUBLIC SYNONYM RESERVATIONS FOR AE.RESERVATIONS;
CREATE PUBLIC SYNONYM MAINTENANCE  FOR AE.MAINTENANCE;


-- Add new aircraft
GRANT EXECUTE ON add_new_aircraft TO ADMIN_AEROPORT;
GRANT EXECUTE ON add_new_aircraft TO RESPONSABLE_VOLS;
GRANT EXECUTE ON add_new_aircraft TO RESPONSABLE_MAINTENANCE;

-- Update aircraft
GRANT EXECUTE ON update_aircraft TO ADMIN_AEROPORT;
GRANT EXECUTE ON update_aircraft TO RESPONSABLE_VOLS;
GRANT EXECUTE ON update_aircraft TO RESPONSABLE_MAINTENANCE;

-- Delete aircraft
GRANT EXECUTE ON delete_aircraft TO ADMIN_AEROPORT;
GRANT EXECUTE ON delete_aircraft TO RESPONSABLE_VOLS;

CREATE PUBLIC SYNONYM seq_logs FOR AE.seq_logs;
-- Select aircraft
GRANT EXECUTE ON select_aircraft_by_id TO ADMIN_AEROPORT;
GRANT EXECUTE ON select_aircraft_by_id TO RESPONSABLE_VOLS;
GRANT EXECUTE ON select_aircraft_by_id TO RESPONSABLE_MAINTENANCE;
GRANT EXECUTE ON select_aircraft_by_id TO AGENT_BILLETERIE;
GRANT EXECUTE ON select_aircraft_by_id TO AGENT_CONTROLE;


-- Add new aircraft
CREATE PUBLIC SYNONYM add_new_aircraft FOR AE.add_new_aircraft;

-- Update aircraft
CREATE PUBLIC SYNONYM update_aircraft FOR AE.update_aircraft;

-- Delete aircraft
CREATE PUBLIC SYNONYM delete_aircraft FOR AE.delete_aircraft;

-- Select aircraft
CREATE PUBLIC SYNONYM select_aircraft_by_id FOR AE.select_aircraft_by_id;



-- ADMIN_AEROPORT can execute all flight procedures
GRANT EXECUTE ON AE.add_new_flight       TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.update_flight        TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.delete_flight        TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.change_flight_state  TO ADMIN_AEROPORT;

-- RESPONSABLE_VOLS can execute all flight procedures
GRANT EXECUTE ON AE.add_new_flight       TO RESPONSABLE_VOLS;
GRANT EXECUTE ON AE.update_flight        TO RESPONSABLE_VOLS;
GRANT EXECUTE ON AE.delete_flight        TO RESPONSABLE_VOLS;
GRANT EXECUTE ON AE.change_flight_state  TO RESPONSABLE_VOLS;

-- AGENT_ENREGISTREMENT can only add and update flights? 
-- (Optional: you can restrict if needed)
GRANT EXECUTE ON AE.add_new_flight       TO AGENT_ENREGISTREMENT;
GRANT EXECUTE ON AE.update_flight        TO AGENT_ENREGISTREMENT;


-- Public synonyms so other users can call without schema prefix
CREATE OR REPLACE PUBLIC SYNONYM add_new_flight FOR AE.add_new_flight;
CREATE OR REPLACE PUBLIC SYNONYM update_flight FOR AE.update_flight;
CREATE OR REPLACE PUBLIC SYNONYM delete_flight FOR AE.delete_flight;
CREATE OR REPLACE PUBLIC SYNONYM change_flight_state FOR AE.change_flight_state;



-- Public synonyms for passengers procedures
CREATE OR REPLACE PUBLIC SYNONYM add_new_passenger FOR AE.add_new_passenger;
CREATE OR REPLACE PUBLIC SYNONYM update_passenger FOR AE.update_passenger;
CREATE OR REPLACE PUBLIC SYNONYM delete_passenger FOR AE.delete_passenger;
CREATE OR REPLACE PUBLIC SYNONYM get_passenger_by_passport FOR AE.get_passenger_by_passport;


-- ADMIN_AEROPORT can do everything with passengers
GRANT EXECUTE ON AE.add_new_passenger            TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.update_passenger             TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.delete_passenger             TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.get_passenger_by_passport    TO ADMIN_AEROPORT;

-- AGENT_ENREGISTREMENT can add and update passengers (register them)
GRANT EXECUTE ON AE.add_new_passenger            TO AGENT_ENREGISTREMENT;
GRANT EXECUTE ON AE.update_passenger             TO AGENT_ENREGISTREMENT;
GRANT EXECUTE ON AE.get_passenger_by_passport    TO AGENT_ENREGISTREMENT;

-- RESPONSABLE_MAINTENANCE can only view passengers (get by passport)
GRANT EXECUTE ON AE.get_passenger_by_passport    TO RESPONSABLE_MAINTENANCE;

-- AGENT_BILLETERIE and AGENT_CONTROLE can only view passengers
GRANT EXECUTE ON AE.get_passenger_by_passport    TO AGENT_BILLETERIE;
GRANT EXECUTE ON AE.get_passenger_by_passport    TO AGENT_CONTROLE;

--------------
-- Public synonyms so users can call procedures without schema prefix
CREATE OR REPLACE PUBLIC SYNONYM add_new_reservation FOR AE.add_new_reservation;
CREATE OR REPLACE PUBLIC SYNONYM update_reservation  FOR AE.update_reservation;
CREATE OR REPLACE PUBLIC SYNONYM delete_reservation  FOR AE.delete_reservation;
CREATE OR REPLACE PUBLIC SYNONYM get_reservation_by_passport FOR AE.get_reservation_by_passport;

-- Grant EXECUTE on reservations procedures

-- ADMIN_AEROPORT: full access
GRANT EXECUTE ON AE.add_new_reservation       TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.update_reservation        TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.delete_reservation        TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.get_reservation_by_passport TO ADMIN_AEROPORT;

-- AGENT_ENREGISTREMENT: add and update only
GRANT EXECUTE ON AE.add_new_reservation TO AGENT_ENREGISTREMENT;
GRANT EXECUTE ON AE.update_reservation  TO AGENT_ENREGISTREMENT;

-- AGENT_BILLETERIE: read access only (get by passport)
GRANT EXECUTE ON AE.get_reservation_by_passport TO AGENT_BILLETERIE;

-- RESPONSABLE_VOLS: full access
GRANT EXECUTE ON AE.add_new_reservation       TO RESPONSABLE_VOLS;
GRANT EXECUTE ON AE.update_reservation        TO RESPONSABLE_VOLS;
GRANT EXECUTE ON AE.delete_reservation        TO RESPONSABLE_VOLS;
GRANT EXECUTE ON AE.get_reservation_by_passport TO RESPONSABLE_VOLS;


-- Maintenance procedures
CREATE OR REPLACE PUBLIC SYNONYM add_new_maintenance FOR AE.add_new_maintenance;
CREATE OR REPLACE PUBLIC SYNONYM update_maintenance FOR AE.update_maintenance;
CREATE OR REPLACE PUBLIC SYNONYM delete_maintenance FOR AE.delete_maintenance;
CREATE OR REPLACE PUBLIC SYNONYM list_maintenance FOR AE.list_maintenance;
CREATE OR REPLACE PUBLIC SYNONYM get_maintenance_by_id FOR AE.get_maintenance_by_id;


-- ADMIN_AEROPORT can execute all maintenance procedures
GRANT EXECUTE ON AE.ADD_NEW_MAINTENANCE       TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.UPDATE_MAINTENANCE       TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.DELETE_MAINTENANCE       TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.LIST_MAINTENANCE         TO ADMIN_AEROPORT;
GRANT EXECUTE ON AE.GET_MAINTENANCE_BY_ID    TO ADMIN_AEROPORT;

-- RESPONSABLE_MAINTENANCE can execute all maintenance procedures
GRANT EXECUTE ON AE.ADD_NEW_MAINTENANCE       TO RESPONSABLE_MAINTENANCE;
GRANT EXECUTE ON AE.UPDATE_MAINTENANCE       TO RESPONSABLE_MAINTENANCE;
GRANT EXECUTE ON AE.DELETE_MAINTENANCE       TO RESPONSABLE_MAINTENANCE;
GRANT EXECUTE ON AE.LIST_MAINTENANCE         TO RESPONSABLE_MAINTENANCE;
GRANT EXECUTE ON AE.GET_MAINTENANCE_BY_ID    TO RESPONSABLE_MAINTENANCE;




SELECT * FROM USER_TAB_PRIVS WHERE TABLE_NAME = 'AE.AIRCRAFT';