CREATE ROLE ADMIN_AEROPORT;
CREATE ROLE AGENT_ENREGISTREMENT;
CREATE ROLE AGENT_CONTROLE;
CREATE ROLE RESPONSABLE_VOLS;
CREATE ROLE RESPONSABLE_MAINTENANCE;
CREATE ROLE AGENT_BILLETERIE;
CREATE ROLE LOGER;


-- LOGER PRIVILEGE
GRANT CREATE SESSION TO LOGER;


--ADMIN PRIVILEGE
GRANT SELECT, INSERT, UPDATE, DELETE
ON PASSENGERS, FLIGHTS, AIRCRAFTS, RESERVATIONS, MAINTENANCE
TO ADMIN_AEROPORT;


-- AGENT_ENREGISTREMENT PRIVILEGE
GRANT SELECT, INSERT, UPDATE
ON PASSENGERS, RESERVATIONS
TO AGENT_ENREGISTREMENT;

GRANT SELECT
ON FLIGHTS
TO AGENT_ENREGISTREMENT;


-- AGENT_CONTROLE PRIVILEGE
GRANT SELECT
ON PASSENGERS, FLIGHTS
TO AGENT_CONTROLE;



-- RESPONSABLE_VOLS PRIVILEGE
GRANT SELECT, INSERT, UPDATE, DELETE
ON FLIGHTS
TO RESPONSABLE_VOLS;

GRANT SELECT
ON AIRCRAFTS
TO RESPONSABLE_VOLS;


-- RESPONSABLE_MAINTENANCE PRIVILEGE
GRANT SELECT, INSERT, UPDATE
ON MAINTENANCE
TO RESPONSABLE_MAINTENANCE;

GRANT SELECT, UPDATE
ON AIRCRAFTS
TO RESPONSABLE_MAINTENANCE;


-- AGENT_BILLETERIE
GRANT SELECT, UPDATE
ON RESERVATIONS
TO AGENT_BILLETERIE;

GRANT SELECT
ON FLIGHTS, PASSENGERS
TO AGENT_BILLETERIE;

