-- Step 1: Create roles
CREATE ROLE ADMIN_AEROPORT;
CREATE ROLE AGENT_ENREGISTREMENT;
CREATE ROLE AGENT_CONTROLE;
CREATE ROLE RESPONSABLE_VOLS;
CREATE ROLE RESPONSABLE_MAINTENANCE;
CREATE ROLE AGENT_BILLETERIE;
CREATE ROLE LOGER;

-- Step 2: LOGER privilege (for login)
GRANT CREATE SESSION TO LOGER;

-- Step 3: ADMIN privileges
GRANT SELECT, INSERT, UPDATE, DELETE
ON PASSENGERS, FLIGHTS, AIRCRAFTS, RESERVATIONS, MAINTENANCE
TO ADMIN_AEROPORT;

-- Step 4: AGENT_ENREGISTREMENT privileges
GRANT SELECT, INSERT
ON PASSENGERS, RESERVATIONS, FLIGHTS
TO AGENT_ENREGISTREMENT;

-- Step 5: AGENT_CONTROLE privileges
GRANT SELECT
ON PASSENGERS, FLIGHTS
TO AGENT_CONTROLE;

-- Step 6: RESPONSABLE_VOLS privileges
GRANT SELECT, INSERT, UPDATE, DELETE
ON FLIGHTS
TO RESPONSABLE_VOLS;

GRANT SELECT
ON AIRCRAFTS
TO RESPONSABLE_VOLS;

-- Step 7: RESPONSABLE_MAINTENANCE privileges
GRANT SELECT, INSERT, UPDATE
ON AIRCRAFTS
TO RESPONSABLE_MAINTENANCE;

GRANT SELECT, UPDATE
ON RESERVATIONS
TO RESPONSABLE_MAINTENANCE;

-- Step 8: AGENT_BILLETERIE privileges
GRANT SELECT, UPDATE
ON RESERVATIONS
TO AGENT_BILLETERIE;

GRANT SELECT
ON FLIGHTS, PASSENGERS
TO AGENT_BILLETERIE;
