-- we will first, create the roles, and then, the users after that.

CREATE ROLE ADMIN_AEROPORT, AGENT_ENREGISTREMENT, AGENT_CONTROLE, RESPONSABLE_VOLS, RESPONSABLE_MAINTENANCE, AGENT_BILLETERIE, LOGER;

-- LOGER PRIVILEGE
GRANT CREATE SESSION TO LOGER;


--ADMIN PRIVILEGE
GRANT SELECT, INSERT, UPDATE, DELETE
ON PASSENGERS, FLIGHTS, AIRCRAFTS, RESERVATIONS, MAINTENANCE
TO ADMIN_AEROPORT;


-- AGENT_ENREGISTREMENT PRIVILEGE
GRANT SELECT, INSERT
ON PASSENGERS, RESERVATIONS, FLIGHTS
TO AGENT_ENREGISTREMENT;

-- AGENT_CONTROLE PRIVILEGE
GRANT SELECT
ON PASSENGERS, FLIGHTS
TO AGENT_CONTROLE;


-- RESPONSABLE_VOLS PRIVILEGE
GRANT SELECT, INSERT, UPDATE, DELETE
ON FLIGHTS
TO RESPONSABLE_VOLS;

GRANT SELECT
ON AIRCRAFTS
TO RESPONSABLE_VOLS;


-- RESPONSABLE_MAINTENANCE PRIVILEGE
GRANT SELECT, INSERT, UPDATE
ON AIRCRAFTS
TO RESPONSABLE_MAINTENANCE;

GRANT SELECT UPDATE
ON RESERVATIONS
TO RESPONSABLE_MAINTENANCE;

-- AGENT_BILLETERIE
GRANT SELECT, UPDATE
ON RESERVATIONS
TO AGENT_BILLETERIE;

GRANT SELECT
ON FLIGHTS, PASSENGERS
TO AGENT_BILLETERIE;
